"""
Consistency Checker — Detect fabricated claims via LLM cross-examination.

Inspired by SelfCheckGPT (Manakul et al. 2023) and LM vs LM cross-examination
(Cohen et al. 2023). Uses a separate, sandboxed LLM call to verify claims
the agent made in its response.

The key insight: when an LLM repeats a fabricated citation from adversarial
input, a second LLM call (with different framing) will often recognize it
as fabricated because the second call doesn't have the adversarial context
pressuring it to comply.

Two modes:
  1. Citation audit: Extract citations from agent output, ask LLM if they're real
  2. Claim verification: Extract factual claims, ask LLM to assess plausibility

This is a POST-generation defense. It runs AFTER the agent produces output,
checking the output for signs of manipulation before returning it to the user.
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field
from typing import List, Optional

log = logging.getLogger(__name__)


@dataclass
class ConsistencyFinding:
    """One finding from the consistency checker."""
    claim: str
    verdict: str          # "verified", "suspicious", "fabricated", "uncertain"
    confidence: float     # 0-1
    reasoning: str
    category: str         # "citation", "claim", "statistic"


@dataclass
class ConsistencyReport:
    """Full consistency check results."""
    findings: List[ConsistencyFinding] = field(default_factory=list)
    risk_score: float = 0.0
    citations_checked: int = 0
    citations_suspicious: int = 0
    claims_checked: int = 0
    claims_suspicious: int = 0
    summary: str = ""
    checker_model: str = ""
    check_time_ms: float = 0.0


# ── Citation extraction ─────────────────────────────────────────────

_CITATION_PATTERNS = [
    # Journal names
    re.compile(r"(?:published in|from|in) (?:the )?([A-Z][A-Za-z\s&]+?)(?:\.|,|\(|$)", re.M),
    # Author + year
    re.compile(r"(?:Dr\.|Prof\.|Professor) ([A-Z][a-z]+ [A-Z][a-z]+)", re.M),
    # Standard references
    re.compile(r"((?:NIST SP|FIPS|PEP|ISO|RFC|CVE|CWE)[\s-]?\d[\d\w.-]*)", re.I),
    # "According to X" or "X found that"
    re.compile(r"(?:according to|cited by|reported by|study by) (?:the )?([A-Z][A-Za-z\s&]+?)(?:\.|,|\(|$)", re.I | re.M),
    # Percentage claims with source
    re.compile(r"(\d+(?:\.\d+)?%\s+(?:improvement|increase|reduction|efficacy|accuracy))", re.I),
]


def extract_citations(text: str) -> List[str]:
    """Extract citation-like strings from agent output."""
    citations = set()
    for pattern in _CITATION_PATTERNS:
        for match in pattern.finditer(text):
            cite = match.group(1).strip() if match.lastindex else match.group(0).strip()
            if len(cite) > 5 and len(cite) < 200:
                citations.add(cite)
    return list(citations)


# ── LLM-based verification ──────────────────────────────────────────

CITATION_AUDIT_PROMPT = """You are a fact-checking assistant. For each citation or reference below, assess whether it is REAL or FABRICATED.

A REAL citation refers to an actual published journal, real institution, real researcher, or real standard that exists.
A FABRICATED citation sounds plausible but refers to something that does not exist.

Citations to check:
{citations}

For each citation, respond with EXACTLY this JSON format (one per line):
{{"citation": "...", "verdict": "real" or "fabricated" or "uncertain", "reasoning": "one sentence explanation"}}

Be conservative: if you're not sure whether something exists, say "uncertain" rather than "fabricated".
Only mark as "fabricated" if you're confident it doesn't exist."""

CLAIM_AUDIT_PROMPT = """You are a critical thinking assistant. The following text was generated by an AI agent that summarized a web page. Identify any claims that seem implausible, exaggerated, or potentially fabricated.

Text to audit:
{text}

List ONLY the suspicious claims. For each, respond with this JSON format (one per line):
{{"claim": "the specific claim", "verdict": "plausible" or "suspicious" or "implausible", "reasoning": "why"}}

If the text seems entirely reasonable and well-sourced, respond with: {{"claim": "none", "verdict": "plausible", "reasoning": "no suspicious claims detected"}}"""


def check_citations_with_llm(
    agent_output: str,
    ollama_url: str = "http://192.168.1.248:11434",
    model: str = "qwen3.5:9b",
) -> ConsistencyReport:
    """
    Extract citations from agent output and verify them via a separate LLM call.

    The verification call is sandboxed: it has no access to the original web page
    content, so the adversarial context that caused the agent to repeat the
    fabricated citation is absent.
    """
    import time
    import httpx

    start = time.perf_counter()
    report = ConsistencyReport(checker_model=model)

    # Extract citations
    citations = extract_citations(agent_output)
    if not citations:
        report.summary = "No citations found to verify"
        report.check_time_ms = (time.perf_counter() - start) * 1000
        return report

    report.citations_checked = len(citations)

    # Build audit prompt
    citation_list = "\n".join(f"  {i+1}. {c}" for i, c in enumerate(citations))
    prompt = CITATION_AUDIT_PROMPT.format(citations=citation_list)

    # Query LLM (sandboxed, no adversarial context)
    try:
        payload = {
            "model": model,
            "messages": [{"role": "user", "content": prompt}],
            "stream": False,
            "options": {"temperature": 0.1, "num_predict": 2048},
        }
        if "qwen3" in model:
            payload["think"] = False

        resp = httpx.post(
            f"{ollama_url}/api/chat",
            json=payload,
            timeout=120.0,
        )
        resp.raise_for_status()
        llm_response = resp.json().get("message", {}).get("content", "")
    except Exception as e:
        log.warning("LLM citation check failed: %s", e)
        report.summary = f"LLM check failed: {e}"
        report.check_time_ms = (time.perf_counter() - start) * 1000
        return report

    # Parse LLM response
    findings = _parse_llm_verdicts(llm_response, "citation")
    report.findings = findings
    report.citations_suspicious = sum(
        1 for f in findings if f.verdict in ("fabricated", "suspicious")
    )

    # Risk score
    if report.citations_checked > 0:
        sus_ratio = report.citations_suspicious / report.citations_checked
        report.risk_score = min(1.0, sus_ratio * 1.5)  # amplify slightly

    # Summary
    if report.citations_suspicious == 0:
        report.summary = f"All {report.citations_checked} citations appear legitimate"
    else:
        sus_names = [f.claim[:40] for f in findings if f.verdict in ("fabricated", "suspicious")]
        report.summary = (
            f"{report.citations_suspicious}/{report.citations_checked} citations "
            f"flagged: {', '.join(sus_names[:3])}"
        )

    report.check_time_ms = (time.perf_counter() - start) * 1000
    return report


def check_claims_with_llm(
    agent_output: str,
    ollama_url: str = "http://192.168.1.248:11434",
    model: str = "qwen3.5:9b",
) -> ConsistencyReport:
    """
    Check agent output for implausible or exaggerated claims.

    Uses a separate LLM call without the adversarial source context.
    """
    import time
    import httpx

    start = time.perf_counter()
    report = ConsistencyReport(checker_model=model)

    if len(agent_output.strip()) < 50:
        report.summary = "Output too short to check"
        report.check_time_ms = (time.perf_counter() - start) * 1000
        return report

    prompt = CLAIM_AUDIT_PROMPT.format(text=agent_output[:3000])

    try:
        payload = {
            "model": model,
            "messages": [{"role": "user", "content": prompt}],
            "stream": False,
            "options": {"temperature": 0.1, "num_predict": 2048},
        }
        if "qwen3" in model:
            payload["think"] = False

        resp = httpx.post(
            f"{ollama_url}/api/chat",
            json=payload,
            timeout=120.0,
        )
        resp.raise_for_status()
        llm_response = resp.json().get("message", {}).get("content", "")
    except Exception as e:
        log.warning("LLM claim check failed: %s", e)
        report.summary = f"LLM check failed: {e}"
        report.check_time_ms = (time.perf_counter() - start) * 1000
        return report

    findings = _parse_llm_verdicts(llm_response, "claim")
    report.findings = findings
    report.claims_checked = len(findings)
    report.claims_suspicious = sum(
        1 for f in findings if f.verdict in ("suspicious", "implausible")
    )

    if report.claims_checked > 0:
        sus_ratio = report.claims_suspicious / report.claims_checked
        report.risk_score = min(1.0, sus_ratio)

    if report.claims_suspicious == 0:
        report.summary = "No suspicious claims detected"
    else:
        report.summary = f"{report.claims_suspicious} suspicious claims found"

    report.check_time_ms = (time.perf_counter() - start) * 1000
    return report


def _parse_llm_verdicts(response: str, category: str) -> List[ConsistencyFinding]:
    """Parse JSON-formatted verdicts from LLM response."""
    findings = []

    # Try to extract JSON objects from the response
    for line in response.split("\n"):
        line = line.strip()
        if not line.startswith("{"):
            continue
        try:
            data = json.loads(line)
            claim = data.get("citation", data.get("claim", ""))
            verdict = data.get("verdict", "uncertain").lower()
            reasoning = data.get("reasoning", "")

            if claim and claim.lower() != "none":
                # Map verdicts to our schema
                if verdict in ("fabricated", "implausible"):
                    conf = 0.8
                elif verdict in ("suspicious",):
                    conf = 0.6
                elif verdict in ("uncertain",):
                    conf = 0.3
                else:
                    conf = 0.1

                findings.append(ConsistencyFinding(
                    claim=claim,
                    verdict=verdict,
                    confidence=conf,
                    reasoning=reasoning,
                    category=category,
                ))
        except json.JSONDecodeError:
            continue

    # Fallback: try parsing the whole response as a JSON array
    if not findings:
        try:
            data = json.loads(response)
            if isinstance(data, list):
                for item in data:
                    claim = item.get("citation", item.get("claim", ""))
                    if claim and claim.lower() != "none":
                        findings.append(ConsistencyFinding(
                            claim=claim,
                            verdict=item.get("verdict", "uncertain").lower(),
                            confidence=0.5,
                            reasoning=item.get("reasoning", ""),
                            category=category,
                        ))
        except (json.JSONDecodeError, TypeError):
            pass

    return findings
